name: polygonid_flutter_sdk_example
description: Demonstrates how to use the polygonid_flutter_sdk plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.2.9+24012901


environment:
  # sdk: ">=2.17.0 <4.0.0"
  sdk: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter

  polygonid_flutter_sdk:
   
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.4
  get_it: ^7.2.05
  intl: ^0.19.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  uuid: ^4.5.0
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  logger: ^2.0.1
  google_mlkit_barcode_scanning: ^0.12.0
  camera: ^0.11.0+2
  #qr_code_scanner: ^1.0.1
  image_picker: ^1.0.0
  envied: ^0.5.4+1
  scan: ^1.6.0
  video_player: ^2.9.1
  google_fonts: ^6.2.1
  gradient_borders: ^1.0.1
  curved_navigation_bar: ^1.0.6
  flutter_spinkit: ^5.2.1
  pretty_qr_code: ^3.3.0
  get_storage: ^2.1.1
  pie_chart: ^5.4.0
  flutter_speed_dial: ^7.0.0
  flutter_slidable: ^3.1.1
  web3modal_flutter: ^3.3.3 
  file_picker: ^8.0.7
  fl_chart: ^0.69.0
  percent_indicator: ^4.2.3
  lottie: ^3.1.2
  hydrated_bloc: ^9.1.5
  flutter_web3: ^2.1.9
  web_socket_channel: ^2.4.4
  package_info_plus: ^7.0.0
  url_launcher: ^6.1.7
  byte_converter: ^1.3.0
  liquid_pull_to_refresh: ^3.0.1
  animated_background: ^2.0.0
  rive: ^0.13.14  
  intl_phone_field: ^3.2.0
  # custom_navigator: ^0.1.1
  loading_animation_widget: ^1.3.0
  awesome_dialog: ^3.2.1
  animated_snack_bar: ^0.4.0




dependency_overrides:
  web_socket_channel: ^2.4.4
  package_info_plus: ^7.0.0
  

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  envied_generator: ^0.5.4+1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  flutter_launcher_icons: "^0.13.1"  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"      
 
  flutter_lints: ^4.0.0


flutter:

 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/abi/
   
    
